# Generated by Django 2.2.12 on 2021-05-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20210520_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'verbose_name': 'registro', 'verbose_name_plural': 'registros'},
        ),
    ]
