# Generated by Django 2.2.12 on 2021-05-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20210520_0422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registro',
        ),
    ]
