# Generated by Django 2.2.12 on 2021-05-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_datos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos',
            new_name='registro',
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'verbose_name': 'registro', 'verbose_name_plural': 'registros'},
        ),
    ]
