# Generated by Django 2.2.12 on 2021-05-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_auto_20210520_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fecha_termino',
            field=models.DateField(default='2021-05-30'),
            preserve_default=False,
        ),
    ]
