# Generated by Django 2.2.12 on 2021-05-30 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_registro_fecha_termino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='fecha_termino',
        ),
    ]
