# Generated by Django 2.2.12 on 2021-05-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0009_remove_registro_fecha_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fecha_termino',
            field=models.DateField(default='2021-05-30'),
            preserve_default=False,
        ),
    ]
